language: r
sudo: required
before_install:
  - make download_neo4j
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
r_github_packages:
  - hadley/testthat
r_packages:
  - roxygen2
script: make test_all