language: r
sudo: required
before_install:
  - make download_neo4j
  - brew update
  - brew tap caskroom/cask
  - brew install brew-cask
  - brew cask install java
r_github_packages:
  - hadley/testthat
r_packages:
  - roxygen2
script: make test_all